name: pgco2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - beautifulsoup4=4.11.1=py37h06a4308_0
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h1ea3ea9_openblas
  - boost=1.70.0=py37h9de70de_1
  - boost-cpp=1.70.0=h8e57a91_2
  - bottleneck=1.3.4=py37hda87dfa_1
  - bs4=4.11.1=hd3eb1b0_0
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py37h43b0acd_1
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - expat=2.4.8=h27087fc_0
  - fontconfig=2.14.0=h8e229c2_0
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h73d1719_1008
  - glib=2.68.4=h9c3ff4c_1
  - glib-tools=2.68.4=h9c3ff4c_1
  - icu=64.2=he1b5a44_1
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libdeflate=1.7=h7f98852_5
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.68.4=h174f98d_1
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.29=ha39b09d_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.21.12=hfc55251_2
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.2.13=h4ab18f5_6
  - lz4-c=1.9.3=h9c3ff4c_1
  - magma=2.5.4=hc72dce7_4
  - mkl=2022.1.0=hc2b9512_224
  - nccl=2.27.3.1=h03a54cd_0
  - ncurses=6.5=h7934f7d_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - ninja=1.13.1=h171cf75_0
  - nomkl=3.0=0
  - numexpr=2.8.0=py37h85a3170_102
  - numpy=1.21.6=py37h976b520_0
  - olefile=0.47=pyhd8ed1ab_0
  - openblas=0.3.29=h06a4308_0
  - openblas-devel=0.3.29=ha39b09d_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.5.2=h26f9b46_0
  - pandas=1.3.5=py37h8c16a72_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.3.2=py37h0f21c89_0
  - pip=22.3.1=py37h06a4308_0
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.3=h0ce48e5_1
  - pycairo=1.21.0=py37h0afab05_1
  - pycparser=2.21=pyhd8ed1ab_0
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.12.1=cuda112py37h6a44366_201
  - pytz=2024.2=pyhd8ed1ab_0
  - readline=8.3=hc2a1206_0
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.8=h1b44611_0
  - soupsieve=2.3.2.post1=py37h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - typing_extensions=4.7.1=pyha770c72_0
  - wheel=0.38.4=py37h06a4308_0
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - alabaster==0.7.13
      - babel==2.14.0
      - charset-normalizer==3.4.3
      - chemprop==1.2.0
      - click==8.1.8
      - cloudpickle==2.2.1
      - cycler==0.11.0
      - docstring-parser==0.16
      - docutils==0.19
      - flask==2.2.5
      - fonttools==4.38.0
      - future==1.0.0
      - hyperopt==0.2.7
      - idna==3.10
      - imagesize==1.4.1
      - importlib-metadata==6.7.0
      - itsdangerous==2.1.2
      - jinja2==3.1.6
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - mypy-extensions==1.0.0
      - packaging==24.0
      - pandas-flavor==0.7.0
      - protobuf==4.24.4
      - py4j==0.10.9.9
      - pygments==2.17.2
      - pyparsing==3.1.4
      - pyyaml==6.0.1
      - rdkit==2023.3.2
      - requests==2.31.0
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - snowballstemmer==3.0.1
      - sphinx==5.3.0
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.1.0
      - tqdm==4.67.1
      - typed-argument-parser==1.8.0
      - typing-inspect==0.9.0
      - urllib3==2.0.7
      - werkzeug==2.2.3
      - xarray==0.20.2
      - zipp==3.15.0
      - "descriptastorus @ git+https://github.com/bp-kelley/descriptastorus"
